### ISSUE TITLE
gcc-6 can now build most of the testsuite successfully 

### ISSUE THREAD

**Issue by octoploid** [boostorg/hana#258]
gcc-6 can now build most of the Hana testsuite successfully, see:
http://www.boost.org/development/tests/develop/developer/hana.html
 (trippels-powerpc64le-gcc-6.0 column)

Maybe it is time to remove the gcc warning:
#warning "You appear to be using GCC, which is not supported by Hana yet."?

**Comment by ldionne** [comment]
I'm still getting around 151 failures with GCC trunk locally, so IMO it's still a bit early to remove the `#warning`. I do agree that many C++14 bugs have been fixed in GCC recently, so it would be worth re-investigating what can be done to support the compiler. That probably means submitting new bug reports, but they're almost there.

**Comment by octoploid** [comment]
Thanks.
I think https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47226 is the only one left.
Maybe you could work around it?
And any new gcc bug report would of course be welcome.

**Comment by octoploid** [comment]
`
example % for f in **/*.cpp ; do echo $f && g++ -O2 -I/var/tmp/hana/include $f && ./a.out ; done
shows:
misc/tree.cpp
Assertion failed: (hana::sum<>(tree) == 10), function main, file misc/tree.cpp, line 134.
scan_right.cpp
Assertion failed: (hana::scan_right(hana::make_tuple(1, "2", '3'), 4, f) == hana::make_tuple( "f(1, f(2, f(3, 4)))", "f(2, f(3, 4))", "f(3, 4)", 4 )), function main, file scan_right.cpp, line 31.
`

**Comment by ldionne** [comment]
With the latest changes I pushed on develop, we should be down to one runtime failure on GCC trunk (in `test/functional/apply.cpp`, caused by [bug 70096](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70096)). Do you know how we can setup Travis CI support for GCC trunk? That would be the next step before I can officially say that GCC is supported.

**Comment by ldionne** [comment]
Also, I can't reproduce the error in `scan_right.cpp`... what platform are you on?

**Comment by octoploid** [comment]
I'm on x86_64 gnu-Linux.

scan_right.cpp only fails if optimizations are enabled:

```
markus@x4 example % g++ -g -I../include scan_right.cpp
markus@x4 example % ./a.out
markus@x4 example % g++ -O2 -g -I../include scan_right.cpp
markus@x4 example % ./a.out
Assertion failed: (hana::scan_right(hana::make_tuple(1, "2", '3'), 4, f) == hana::make_tuple( "f(1, f(2, f(3, 4)))", "f(2, f(3, 4))", "f(3, 4)", 4 )), function main, file scan_right.cpp, line 31.
[1]    27943 abort      ./a.out
```

(I have no idea about gcc-6 Travis CI support)

**Comment by octoploid** [comment]
No. You're invoking undefined behavior, see http://gcc.gnu.org/gcc-6/porting_to.html
(More aggressive optimization of -flifetime-dse).

-flifetime-dse=1 "fixes" the issue.

**Comment by ldionne** [comment]
Thanks, I'm on it. I only ran the tests with GCC in Debug mode.

**Comment by badair** [comment]
> Do you know how we can setup Travis CI support for GCC trunk?

@ldionne I looked into this about a week ago. I don't know how to do this without building from source, which I assume would be highly frowned upon. As far as I can tell, GCC 5.2.1 is the latest package available. I don't know if the same can be said for Appveyor.

**Comment by ldionne** [comment]
@badair Thanks for the info. Building from source will be way too long. That sucks.

**Comment by ldionne** [comment]
@octoploid I fixed the `scan_right` bug locally; I'm testing and I'll push the fix. I'll also run all the tests in release mode with GCC. We're almost there!!!

**Comment by octoploid** [comment]
Thanks. All looks good now. 
commit dd92656da819 can now be reverted, because the gcc bug was fixed.

Compile times look good for gcc:
1500.02s user 78.09s system 380% cpu 6:55.02 total

clang is much slower:
 2122.16s user 58.94s system 285% cpu 12:42.68 total

(make -j4 check with CXXFLAGS="-O2". Both compilers were build with checking=release and asserts enabled.)

**Comment by ldionne** [comment]
Two things: 
1. I'm still getting a segfault in `test.functional.apply` because of [70096](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70096). This appears to be the last problem remaining.
2. How do you build GCC with optimizations enabled? My GCC is a total slowpoke, taking over an hour to complete the test suite.

**Comment by octoploid** [comment]
@ldionne 
1. I build with CXXFLAGS="-O2", so I don't hit the issue.
2. Just configure gcc with --enable-checking=release

BTW github_234.cpp fails on a ppc64le POWER8 machine:

/home/trippels/hana/include/boost/hana/equal.hpp:60:13: error: static assertion failed: No default implementation of hana::equal is provided for related types that can't be safely embedded into a common type, because those are most likely programming errors. If this is really what you want, you can manually convert both objects to a common Comparable type before performing the comparison.
             static_assert(!hana::is_convertible<T_, U>::value &&
             ^~~~~~~~~~~~~

**Comment by ldionne** [comment]
@octoploid  Is it possible that `char` is unsigned on that machine?

**Comment by octoploid** [comment]
Yes and ppc64 is not the only arch:
```
Signed					Unsigned
alpha					aarch64
i686					arm
ia64					ppc
m68k					ppc64
mips					s390
sparc					s390x
x86_64
```

**Comment by gnzlbg** [comment]
There is an open issue for whitelisting GCC 6 on travis (it seems that there are packages for it in ubuntu-toolchain-r-test): 

Issue: https://github.com/travis-ci/apt-package-whitelist/issues/2294

Packages: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

**Comment by ldionne** [comment]
@octoploid Thanks, fixed.
@gnzlbg Looks like we'll have to wait for the Travis team.. Thanks for the cross-reference.

**Comment by ldionne** [comment]
63c5f87dfdadd07e496cefefc63c3ea9968d3140 removes the warning about GCC and documents support for GCC. GCC 6 officially supports Hana!

**Comment by rhalbersma** [comment]
@gnzlbg AFAICS, gcc-6 is only available for the upcoming Ubuntu 16.04 LTS, not yet for 12.04 / 14.04.  Or did you just forcibly install the 16.04 package on an older distro?
